services:
  app:
    image: laravelphp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  webserver:
    image: arm64v8/nginx
    #platform: linux/amd64
    container_name: task_management_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  database:
    image: mysql:8
    container_name: task_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: task_management_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
